name: My First CI Pipeline

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Select test suite'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - regression
jobs:
  test:
    runs-on: ubuntu-latest

    env: 
      Environment : QA

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven tests
        run: mvn test -Dgroups=smoke


      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/

    
